name: Build EPG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */48 * * *"  # Every 2 days

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests lxml

      - name: Merge EPGs
        env:
          IPTV_EPG: https://xtream-ie.org/xmltv.php?username=jBHCENewjm&password=tBQPCewkCU
          NZ_EPG: https://i.mjh.nz/nz/epg.xml
        run: python .github/scripts/merge_epgs.py

      - name: Add show images
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python .github/scripts/add_images.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
